### ISSUE TITLE
Provide Docker image

### ISSUE THREAD

**Issue by metalmatze** [kumina/openvpn_exporter#14]
Hey!
This exporter is exactly what I am looking for. Sadly I don't want to maintain a docker image, which is for obvious reasons going to be outdated every now and then.
Would it be possible to provide a Docker image right away?

**Comment by maksim77** [comment]
As far as I can see in the repository, the docker is ready for a long time.

**Comment by timstoop** [comment]
There was a typo in the docs that @maksim77 fixed, should work now!

**Comment by Ivaylo-Korakov** [comment]
Docker file in the repository. Closing this issue.
