### ISSUE TITLE
No option to install without docker?

### ISSUE THREAD

**Issue by 1medusa1** [kumina/openvpn_exporter#15]
Really thought, assuming rather that this would be ready to go, didn't realise until i got to the bottom that you need docker

**Comment by pieterlange** [comment]
You don't need docker at all, you can just build the source yourself. Docker just makes it easier :whale:

**Comment by 1medusa1** [comment]
i try to build from source but dependencies don't exist, also in the make file it is referencing docker, don't know if this is conflict, 

go build openvpn_exporter.go
openvpn_exporter.go:29:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/lib/go-1.6/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        ($GOPATH not set)
openvpn_exporter.go:30:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
        /usr/lib/go-1.6/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)
        ($GOPATH not set)

**Comment by timstoop** [comment]
It looks like your golang environment is not set up correctly?
Also, we build with Go 1.10, not sure if this even works on Go 1.6...

**Comment by 1medusa1** [comment]
Alrighty, i built it from source. (go1.6) it seems to be working however as @timstoop mentioned due to go versions, i have the following status message:

Failed to scrape showq socket: unexpected file contents: "OpenVPN CLIENT LIS"

Maybe this is because a new OpenVPN version has formatted the data differently so i can't perform the scrape because it is unexpected.

**Comment by micah** [comment]
You need to set an option in your server's config file for it to produce the statistics, look for the `status` option in the documentation for how to do that.

I think this issue could be closed.

**Comment by Ivaylo-Korakov** [comment]
@micah agreed
