### ISSUE TITLE
Failed to scrape showq socket: unexpected file contents: "OpenVPN CLIENT LIS"

### ISSUE THREAD

**Issue by lcorsini** [kumina/openvpn_exporter#16]
EDIT this happens because openvpn by default gives status-version 1

`2018/08/17 14:33:59 Failed to scrape showq socket: unexpected file contents: "OpenVPN CLIENT LIS"
`
the exporter seems to work fine, but I got this error when the scraping happens
openvpn is versione:
`OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD]`
packaged in ubuntu 18.04
this is the content of openvpn-status.log
`
OpenVPN CLIENT LIST
Updated,Fri Aug 17 14:46:34 2018
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
xxx.xxxx.xxx,999.999.999.999:45787,339231182,40182388,Wed Aug 15 20:21:18 2018
xxx.xxxx.xxx,999.999.999.999:36356,238994029,19191293,Wed Aug 15 20:22:08 2018
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
10.8.0.6,xxx.xxxx.xxx,999.999.999.999:36356,Fri Aug 17 14:46:19 2018
10.8.0.10,xxx.xxxx.xxx,999.999.999.999:45787,Fri Aug 17 14:46:30 2018
GLOBAL STATS
Max bcast/mcast queue length,0
END

`

**Comment by tomsnuvv** [comment]
Hi @lcorsini,

We also had this issue and we solved it by setting the status-version to format 2 in the openvpn config.

**Comment by Bulinator** [comment]
Hi,

Even if I set status-version 2 (comma delimited) in configuration server file, the error is still here:

`2019/09/19 08:01:44 Failed to scrape showq socket: unexpected file contents: "OpenVPN CLIENT LIS"`

Installed on Debian 10 & OpenVPN 2.4.0 x86_64-pc-linux-gnu

Any idea ?

**Comment by lijinghuatongxue** [comment]
> Hi @lcorsini,
> 
> We also had this issue and we solved it by setting the status-version to format 2 in the openvpn config.

I have doubts about this place.

root@#:/etc/openvpn# tail -10 ksc-server.conf
#push "route 172.29.207.0 255.255.255.0"
status logs/openvpn-status.log
log-append  logs/openvpn.log
verb 3
status-version 2
;local *.*.*.*

plugin /etc/openvpn/bin/minimal_pf.so
client-connect /etc/openvpn/bin/client-connect.sh
script-security 3
root@#:/etc/openvpn# docker ps
CONTAINER ID        IMAGE                            COMMAND                CREATED             STATUS              PORTS                    NAMES
76386b7dcca4        kumina/openvpn-exporter:latest   "/bin/openvpn_export   About an hour ago   Up About an hour    0.0.0.0:9176->9176/tcp   tender_ardinghelli
root@#:/etc/openvpn# docker logs -f tender_ardinghelli
2019/10/25 17:18:26 Starting OpenVPN Exporter
2019/10/25 17:18:26 Listen address: :9176
2019/10/25 17:18:26 Metrics path: /metrics
2019/10/25 17:18:26 openvpn.status_path: /etc/openvpn_exporter/server.status
2019/10/25 17:34:38 Failed to scrape showq socket: unexpected file contents: ""
2019/10/25 17:39:13 Failed to scrape showq socket: unexpected file contents: ""
2019/10/25 17:39:28 Failed to scrape showq socket: unexpected file contents: ""
2019/10/25 17:39:43 Failed to scrape showq socket: unexpected file contents: ""
2019/10/25 17:39:58 Failed to scrape showq socket: unexpected file contents: ""
2019/10/25 17:40:13 Failed to scrape showq socket: unexpected file contents: ""

**Comment by pradeepspa** [comment]
I am experiencing same issue. Any fix so far?

**Comment by steven166** [comment]
To resolve this issue, start OpenVPN with `--status-version 3`

**Comment by kumy** [comment]
I have a similar error
```
2020/03/26 16:48:05 Failed to scrape showq socket: unexpected file contents: "0\xcc\x03\x00\f\x00\x04\x01.\x00\x00\x007\xcc\x03\x00\f\x00"
```

Setting `--status-version` to `2` or `3` doesn't change anything

Status content:
v2
```
cat /var/etc/openvpn/statuses/server2.status 
OpenVPN CLIENT LIST
Updated,Thu Mar 26 16:42:51 2020
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
GLOBAL STATS
Max bcast/mcast queue length,0
END

```

v3
```
cat /var/etc/openvpn/statuses/server2.status
TITLE	OpenVPN 2.4.6 amd64-portbld-freebsd11.2 [SSL (OpenSSL)] [LZO] [LZ4] [MH/RECVDA] [AEAD] built on Oct  3 2018
TIME	Thu Mar 26 16:49:17 2020	1585237757
HEADER	CLIENT_LIST	Common Name	Real Address	Virtual Address	Virtual IPv6 Address	Bytes Received	Bytes Sent	Connected Since	Connected Since (time_t)	Username	Client ID	Peer ID
HEADER	ROUTING_TABLE	Virtual Address	Common Name	Real Address	Last Ref	Last Ref (time_t)
GLOBAL_STATS	Max bcast/mcast queue length	0
END
```

**Comment by jirib** [comment]
No idea what I do wrong but I have same issue:

```
# rpm -q openvpn ; grep ^status /etc/openvpn/server.conf 
openvpn-2.4.9-1.el7.x86_64
status /var/log/openvpn/status.log 30
status-version 2
```

```
# su -s /bin/sh nobody -c '/usr/local/bin/openvpn_exporter -openvpn.status_paths /var/log/openvpn/status.log'
2020/07/09 14:17:37 Starting OpenVPN Exporter
2020/07/09 14:17:37 Listen address: :9176
2020/07/09 14:17:37 Metrics path: /metrics
2020/07/09 14:17:37 openvpn.status_path: /var/log/openvpn/status.log
2020/07/09 14:17:37 Ignore Individuals: false
2020/07/09 14:17:37 openvpn.status_type: file
^Bo2020/07/09 14:18:34 Failed to scrape showq socket: unsupported key: "CLIENT_LIST"
```

@BartVerc any idea?
