### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by jly26** [kumina/openvpn_exporter#29]
Hi can you please tell how can I install this on my debian vpn server ..grafana and influxdb alreafy install,,TY

**Comment by rayjanoka** [comment]
Hi @jly26,
 
Install golang
```sudo apt install golang-go```

Install openvpn_exporter
```go get -u github.com/kumina/openvpn_exporter```

Add the go bin folder to $PATH
```export PATH=$PATH:/home/ubuntu/go/bin```

run it
```$ openvpn_exporter
2020/06/16 17:24:07 Starting OpenVPN Exporter
2020/06/16 17:24:07 Listen address: :9176
2020/06/16 17:24:07 Metrics path: /metrics
```
