### ISSUE TITLE
not working with openvpn 2.4.3

### ISSUE THREAD

**Issue by Sispheor** [kumina/openvpn_exporter#7]
```
openvpn --version
OpenVPN 2.4.3 x86_64-redhat-linux-gnu [Fedora EPEL patched] [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jun 21 2017
```

Example of generated status file I have
```
OpenVPN CLIENT LIST
Updated,Mon Nov 20 10:11:52 2017
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
UNDEF,16.17.101.136,145939323,361988340,Thu Nov 16 19:05:34 2017
UNDEF,16.17.99.242,5085293,5335505,Thu Nov 16 19:05:28 2017
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
30.100.5.222,UNDEF,16.16.91.230,Sat Nov 18 07:03:24 2017
30.100.2.142,UNDEF,16.17.99.242,Fri Nov 17 15:49:16 2017
GLOBAL STATS
Max bcast/mcast queue length,0
END
```

The parsing function fail to recognize the type of version.

**Comment by EdSchouten** [comment]
Hi there!

I just looked through the OpenVPN code. It seems that this type of output corresponds with server statistics version 1. This exporter is designed only to support the formats generated with `--status-version 2` and `--status-version 3`. Be sure to confirm whether passing in these flags makes this exporter work for you. Thanks

Ed

**Comment by Sispheor** [comment]
Oh ok thanks !
